[package]
name = "mango-v4-arbi-bot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "arbi-bot"
path = "src/main.rs"

[dependencies]
anchor-client = { path = "../../3rdparty/anchor/client" }
anchor-lang = { path = "../../3rdparty/anchor/lang" }
anchor-spl = { path = "../../3rdparty/anchor/spl" }
anyhow = "1.0"
clap = { version = "3.1.8", features = ["derive", "env"] }
dotenv = "0.15.0"
env_logger = "0.8.4"
fixed = { path = "../../3rdparty/fixed", version = "1.11.0", features = ["serde", "borsh"] }
futures = "0.3.21"
log = "0.4.0"
mango-v4 = { path = "../../programs/mango-v4", features = ["client"] }
mango-v4-client = { path = "../../lib/client" }
pyth-sdk-solana = "0.1.0"
serum_dex = { git = "https://github.com/openbook-dex/program.git", default-features=false,features = ["no-entrypoint", "program"] }
solana-client = "~1.14.9"
solana-rpc = "~1.14.9"
solana-sdk = "~1.14.9"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ws", "http", "tls"] }


tokio = { version = "1.14.1", features = ["rt-multi-thread", "time", "macros", "sync"] }
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.24", features = ["serde"] }

tokio-tungstenite = { version = "0.17.2", features = ["native-tls"] }
itertools = "0.10.5"
ordered-float = "3.7.0"
url = "2.3.1"
reqwest = { version = "0.11.17", features = ["json"] }

